<?php

namespace Samane\Proxies\__CG__;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Agence extends \Agence implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Agence' . "\0" . 'id', '' . "\0" . 'Agence' . "\0" . 'libelle', '' . "\0" . 'Agence' . "\0" . 'adresse', '' . "\0" . 'Agence' . "\0" . 'standard', '' . "\0" . 'Agence' . "\0" . 'created_at', '' . "\0" . 'Agence' . "\0" . 'numero_agence', '' . "\0" . 'Agence' . "\0" . 'comptes', '' . "\0" . 'Agence' . "\0" . 'employes', '' . "\0" . 'Agence' . "\0" . 'caisses'];
        }

        return ['__isInitialized__', '' . "\0" . 'Agence' . "\0" . 'id', '' . "\0" . 'Agence' . "\0" . 'libelle', '' . "\0" . 'Agence' . "\0" . 'adresse', '' . "\0" . 'Agence' . "\0" . 'standard', '' . "\0" . 'Agence' . "\0" . 'created_at', '' . "\0" . 'Agence' . "\0" . 'numero_agence', '' . "\0" . 'Agence' . "\0" . 'comptes', '' . "\0" . 'Agence' . "\0" . 'employes', '' . "\0" . 'Agence' . "\0" . 'caisses'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Agence $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getLibelle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLibelle', []);

        return parent::getLibelle();
    }

    /**
     * {@inheritDoc}
     */
    public function setLibelle($libelle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLibelle', [$libelle]);

        return parent::setLibelle($libelle);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse', []);

        return parent::getAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse($adresse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse', [$adresse]);

        return parent::setAdresse($adresse);
    }

    /**
     * {@inheritDoc}
     */
    public function getStandard()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStandard', []);

        return parent::getStandard();
    }

    /**
     * {@inheritDoc}
     */
    public function setStandard($standard)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStandard', [$standard]);

        return parent::setStandard($standard);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreated_at()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreated_at', []);

        return parent::getCreated_at();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreated_at($created_at)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreated_at', [$created_at]);

        return parent::setCreated_at($created_at);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumero_agence()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumero_agence', []);

        return parent::getNumero_agence();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumero_agence($numero_agence)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumero_agence', [$numero_agence]);

        return parent::setNumero_agence($numero_agence);
    }

    /**
     * {@inheritDoc}
     */
    public function getComptes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComptes', []);

        return parent::getComptes();
    }

    /**
     * {@inheritDoc}
     */
    public function setComptes($comptes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComptes', [$comptes]);

        return parent::setComptes($comptes);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmployes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmployes', []);

        return parent::getEmployes();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmployes($employes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmployes', [$employes]);

        return parent::setEmployes($employes);
    }

    /**
     * {@inheritDoc}
     */
    public function getCaisses()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCaisses', []);

        return parent::getCaisses();
    }

    /**
     * {@inheritDoc}
     */
    public function setCaisses($caisses)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCaisses', [$caisses]);

        return parent::setCaisses($caisses);
    }

}
